config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'

  # get 'pictures' => 'pictures#index'
  # get 'pictures/new' => 'pictures#new' 
  # get 'pictures/:id/edit' => "pictures#edit", as: "edit_picture"
  # get 'pictures/:id' => 'pictures#show', as: 'picture'

  # post 'pictures' => 'pictures#create' 
  # patch 'pictures/:id' => "pictures#update"
  # delete 'pictures/:id' => 'pictures#destroy', as: "delete_picture"

  resources :pictures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    def index
        @pictures = Picture.all
    end

    def show
        @picture = Picture.find(params[:id])
    end

    def new
        @picture = Picture.new
    end

    def create
        # make a new picture with what picture_params returns (which is a method we're calling)
        @picture = Picture.new(picture_params)
        if @picture.save
          # if the save for the picture was successful, go to index.html.erb
          redirect_to pictures_url
        else
          # otherwise render the view associated with the action :new (i.e. new.html.erb)
          render :new
        end
      end

      def edit
        @picture = Picture.find(params[:id])
      end

      def update
        @picture = Picture.find(params[:id])

        if @picture.update_attributes(picture_params)
            redirect_to "/pictures/#{@picture.id}"
          else
            render :edit
          end
      end

      def destroy
        @picture = Picture.find(params[:id])
        @picture.destroy
        redirect_to pictures_url
      end
    
      private
      def picture_params
        params.require(:picture).permit(:artist, :title, :url)
      end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Talgur</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pictures/index.html.erb
<h1> <%= @pictures.length %> Pictures</h1>
<%= link_to "New Picture", "/pictures/new" %>


<% @pictures.each do |picture| %>
  <p><%= picture.title %>, <%= picture.artist %></p>
  <%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
<% end %>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to Pictures", pictures_url %>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %> 

| <%= link_to "Edit", edit_picture_path(@picture) %>

| <%= link_to "Delete", @picture, method: :delete, 
    data: {confirm: "Are you sure you want to delete this picture?"}  %>

<p><%= @picture.title %>, <%= @picture.artist %></p>
<%= image_tag @picture.url %>